[package]
name = "memfile"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
enumflags2 = { version = "0.6.4", features = ["not_literal"] }
libc = "0.2.84"
